[27/Nov/2014 17:26:17] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 129, in processoren
    processorenlijst = stock(processorenlijst, "morgen")
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 313, in stock
    objectlijst -= component
TypeError: unsupported operand type(s) for -=: 'QuerySet' and 'Processoren'
[27/Nov/2014 17:27:31] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 284, in listing
    componenten = paginator.page(pagina)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 17:28:32] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst.objects, 15)
AttributeError: 'set' object has no attribute 'objects'
[27/Nov/2014 17:34:35] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 284, in listing
    componenten = paginator.page(pagina)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 17:35:14] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 284, in listing
    componenten = paginator.page(pagina)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 17:35:15] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 284, in listing
    componenten = paginator.page(pagina)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 17:35:15] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 284, in listing
    componenten = paginator.page(pagina)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 17:35:16] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 284, in listing
    componenten = paginator.page(pagina)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 17:46:28] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 287, in listing
    componenten = paginator.page(1)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 17:53:46] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 287, in listing
    componenten = paginator.page(1)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 18:00:08] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 288, in listing
    componenten = paginator.page(1)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 18:00:49] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 288, in listing
    componenten = paginator.page(1)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 18:15:37] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 137, in processoren
    processoren = listing(request, processorenlijst, 15)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 289, in listing
    componenten = paginator.page(1)
  File "/usr/local/lib/python2.7/dist-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'set' object has no attribute '__getitem__'
[27/Nov/2014 18:17:10] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 129, in processoren
    processorenlijst = stock(processorenlijst, "morgen")
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 311, in stock
    print componentenlijst
NameError: global name 'componentenlijst' is not defined
[27/Nov/2014 18:18:44] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 128, in processoren
    processorenlijst = stock(processorenlijst.objects, "morgen")
UnboundLocalError: local variable 'processorenlijst' referenced before assignment
[27/Nov/2014 18:34:36] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 134, in processoren
    for processoren in processorenlijst:
TypeError: 'NoneType' object is not iterable
[27/Nov/2014 18:35:36] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 129, in processoren
    for processoren in processorenlijst:
TypeError: 'NoneType' object is not iterable
[27/Nov/2014 18:35:37] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 129, in processoren
    for processoren in processorenlijst:
TypeError: 'NoneType' object is not iterable
[27/Nov/2014 18:45:28] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 310
    return levering = request.GET.get('stockcheck')
                    ^
SyntaxError: invalid syntax
[27/Nov/2014 18:46:07] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 310
    return levering = request.GET.get('stockcheck')
                    ^
SyntaxError: invalid syntax
[27/Nov/2014 18:46:55] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 310
    return levering = request.GET.get('stockcheck')
                    ^
SyntaxError: invalid syntax
[27/Nov/2014 18:48:02] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 311
    return levering = request.GET.get('stockcheck')
                    ^
SyntaxError: invalid syntax
[27/Nov/2014 18:48:24] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 314
    return levering = "alles"
                    ^
SyntaxError: invalid syntax
[27/Nov/2014 18:48:25] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 314
    return levering = "alles"
                    ^
SyntaxError: invalid syntax
[27/Nov/2014 18:48:26] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 314
    return levering = "alles"
                    ^
SyntaxError: invalid syntax
[27/Nov/2014 18:48:27] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 314
    return levering = "alles"
                    ^
SyntaxError: invalid syntax
[27/Nov/2014 19:41:55] WARNING [django.request:99] Forbidden (CSRF cookie not set.): /processoren/
[27/Nov/2014 19:43:19] WARNING [django.request:99] Forbidden (CSRF cookie not set.): /processoren/
[27/Nov/2014 19:48:02] WARNING [django.request:99] Forbidden (CSRF cookie not set.): /processoren/
