[28/Oct/2014 10:02:37] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 29, in detail
    context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 23, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 444, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 546, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 410, in _reverse_with_prefix
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 303, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 118, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import pcbuilder.templatetags.keyvalue. View does not exist in module pcbuilder.templatetags.
[28/Oct/2014 10:02:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:03:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:03:42] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 118, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import pcbuilder.views.select. View does not exist in module pcbuilder.views.
[28/Oct/2014 10:03:42] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:04:49] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:04:50] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 25, in select
    product = product.GET.get('product')
UnboundLocalError: local variable 'product' referenced before assignment
[28/Oct/2014 10:04:51] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:05:50] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:05:51] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:05:52] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 27, in select
    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
NameError: global name 'HttpResponseRedirect' is not defined
[28/Oct/2014 10:05:53] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:06:31] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:06:33] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:06:34] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:08:21] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:09:12] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:12:38] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:12:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:16] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:18] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:19] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:32] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:34] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:36] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:38] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:44] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:45] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:50] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:52] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:54] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:56] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:58] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:59] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:01] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:06] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:08] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:09] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:10] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:11] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:30] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:33] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:50] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:17:04] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:17:12] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:19:08] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:20:26] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:20:44] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:20:46] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:20:47] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:22:46] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:22:48] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:24:36] WARNING [django.request:143] Not Found: /favicon.ico
