[30/Nov/2014 11:51:17] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:51:46] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    #processoren = json.dumps(list(uniArray))
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:55:08] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:55:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs.translate("\u20AC")
AttributeError: 'list' object has no attribute 'translate'
[30/Nov/2014 11:56:07] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140
    diestringnaam = processoren.prijs[].translate("\u20AC")
                                      ^
SyntaxError: invalid syntax
[30/Nov/2014 11:56:13] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[1].translate("\u20AC")
IndexError: list index out of range
[30/Nov/2014 11:56:24] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate("\u20AC")
IndexError: list index out of range
[30/Nov/2014 11:56:26] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate("\u20AC")
IndexError: list index out of range
[30/Nov/2014 11:56:27] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate("\u20AC")
IndexError: list index out of range
[30/Nov/2014 11:56:41] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:56:42] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:56:42] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:56:43] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:56:43] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:56:44] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:56:44] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:56:44] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:56:45] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:51] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:53] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:53] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:53] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:53] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:57:54] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:58:07] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:17] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:54] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:55] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:55] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:55] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:56] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:56] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:56] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:56] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:57] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:57] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:57] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:57] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:57] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 11:59:58] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 12:00:51] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:53] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:53] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:54] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:54] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:54] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:54] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:55] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:00:55] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 140, in processoren
    diestringnaam = processoren.prijs[0].translate( None, u'\u20ac')
TypeError: translate() takes exactly one argument (2 given)
[30/Nov/2014 12:01:24] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 12:46:34] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 12:46:36] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rik/A-Pc/Website/pcbuilder/views.py", line 141, in processoren
    if float(diestringnaam) < float(minPriceSliderValue):
UnicodeEncodeError: 'decimal' codec can't encode character u'\u20ac' in position 0: invalid decimal Unicode string
[30/Nov/2014 19:27:25] WARNING [django.request:143] Not Found: /favicon.ico
[30/Nov/2014 20:25:41] WARNING [django.request:143] Not Found: /favicon.ico
[30/Nov/2014 20:35:42] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 7
    form django.utils import simplejson
              ^
SyntaxError: invalid syntax
[30/Nov/2014 20:35:55] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 7, in <module>
    from django.utils import simplejson
ImportError: cannot import name simplejson
[30/Nov/2014 20:38:05] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 7, in <module>
    from django.utils import json
ImportError: cannot import name json
[30/Nov/2014 20:38:58] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 155, in processoren
    return HttpResponse(simplejson.dumps(to_json), mimetype='application/json')
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Page 1 of 11> is not JSON serializable
[30/Nov/2014 20:39:22] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 155, in processoren
    return HttpResponse(simplejson.dumps(to_json), mimetype='application/json')
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Page 1 of 11> is not JSON serializable
[30/Nov/2014 20:46:18] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 155, in processoren
    return HttpResponse(simplejson.dumps(to_json), mimetype='application/json')
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Page 1 of 11> is not JSON serializable
[30/Nov/2014 20:52:55] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 158
    return render_to_response('processoren.html', {'Componenten': processoren, 'Range':bereik, 'Diff':diff, "minPriceSliderValue":minPriceSliderValue , "maxPriceSliderValue":maxPriceSliderValue },
         ^
IndentationError: expected an indented block
[30/Nov/2014 20:52:56] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 158
    return render_to_response('processoren.html', {'Componenten': processoren, 'Range':bereik, 'Diff':diff, "minPriceSliderValue":minPriceSliderValue , "maxPriceSliderValue":maxPriceSliderValue },
         ^
IndentationError: expected an indented block
[30/Nov/2014 20:53:52] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 158
    return render_to_response('processoren.html', {'Componenten': processoren, 'Range':bereik, 'Diff':diff, "minPriceSliderValue":minPriceSliderValue , "maxPriceSliderValue":maxPriceSliderValue },
         ^
IndentationError: expected an indented block
[30/Nov/2014 20:54:11] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 155, in processoren
    component['processoren'] = model_to_dict(component["processoren"])
NameError: global name 'model_to_dict' is not defined
[30/Nov/2014 20:54:40] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 156, in processoren
    component['processoren'] = model_to_dict(component["processoren"])
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/document.py", line 179, in __getitem__
    raise KeyError(name)
KeyError: 'processoren'
[30/Nov/2014 20:57:35] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 154, in processoren
    json.dumps(processoren, cls=MongoEncoder)
NameError: global name 'MongoEncoder' is not defined
[30/Nov/2014 20:58:49] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 154
    return HttpResponse(json.dumps(list(projects.bojects.all().values))), mimetype='application/json')
                                                                                  ^
SyntaxError: invalid syntax
[30/Nov/2014 20:59:07] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 154
    return HttpResponse(simplejson.dumps(list(projects.bojects.all().values))), mimetype='application/json')
                                                                                        ^
SyntaxError: invalid syntax
[30/Nov/2014 20:59:08] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 154
    return HttpResponse(simplejson.dumps(list(projects.bojects.all().values))), mimetype='application/json')
                                                                                        ^
SyntaxError: invalid syntax
