[28/Oct/2014 10:02:37] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 29, in detail
    context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 23, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 444, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 546, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 410, in _reverse_with_prefix
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 303, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 118, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import pcbuilder.templatetags.keyvalue. View does not exist in module pcbuilder.templatetags.
[28/Oct/2014 10:02:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:03:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:03:42] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 118, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import pcbuilder.views.select. View does not exist in module pcbuilder.views.
[28/Oct/2014 10:03:42] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:04:49] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:04:50] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 25, in select
    product = product.GET.get('product')
UnboundLocalError: local variable 'product' referenced before assignment
[28/Oct/2014 10:04:51] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:05:50] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:05:51] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:05:52] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 27, in select
    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
NameError: global name 'HttpResponseRedirect' is not defined
[28/Oct/2014 10:05:53] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:06:31] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:06:33] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:06:34] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:08:21] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:09:12] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:12:38] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:12:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:16] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:18] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:19] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:32] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:34] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:36] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:38] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:44] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:45] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:50] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:52] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:54] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:56] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:58] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:15:59] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:01] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:06] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:08] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:09] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:10] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:11] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:30] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:33] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:16:50] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:17:04] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:17:12] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:19:08] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:20:26] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:20:44] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:20:46] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:20:47] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:22:46] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:22:48] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:24:36] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:27:36] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:27:37] ERROR [django.request:231] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 23, in index
    context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 23, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 201, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 175, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 974, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 906, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/smartif.py", line 164, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/local/lib/python2.7/dist-packages/django/template/smartif.py", line 175, in translate_token
    return self.create_var(token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 909, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
[28/Oct/2014 10:27:38] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:27:53] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:28:18] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:28:23] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:28:52] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 29, in select
    request.session[categorie + "naam"] = product
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[28/Oct/2014 10:28:53] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:28:58] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:29:18] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:29:19] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:29:21] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:06] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:08] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:09] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:11] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:18] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:44] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:46] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 27, in select
    categorie = request.GET.getw('categorie')
AttributeError: 'QueryDict' object has no attribute 'getw'
[28/Oct/2014 10:33:47] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:55] INFO [root:28] None
[28/Oct/2014 10:33:55] INFO [root:29] test
[28/Oct/2014 10:33:55] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:33:57] INFO [root:28] None
[28/Oct/2014 10:33:57] INFO [root:29] test
[28/Oct/2014 10:33:57] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:35:57] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:36:01] ERROR [django.request:231] Internal Server Error: /select/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 27, in select
    categorie = request.GET.getw('categorie')
AttributeError: 'QueryDict' object has no attribute 'getw'
[28/Oct/2014 10:36:01] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:36:13] ERROR [pcbuilder.views:29] None
[28/Oct/2014 10:36:13] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:36:15] ERROR [pcbuilder.views:29] None
[28/Oct/2014 10:36:15] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:36:18] ERROR [pcbuilder.views:29] None
[28/Oct/2014 10:36:18] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:36:22] ERROR [pcbuilder.views:29] None
[28/Oct/2014 10:36:23] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:37:13] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:37:14] DEBUG [pcbuilder.views:29] None
[28/Oct/2014 10:37:15] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:37:30] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:37:31] DEBUG [pcbuilder.views:29] None
[28/Oct/2014 10:37:31] DEBUG [pcbuilder.views:30] test
[28/Oct/2014 10:37:32] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:37:35] DEBUG [pcbuilder.views:29] None
[28/Oct/2014 10:37:35] DEBUG [pcbuilder.views:30] test
[28/Oct/2014 10:37:35] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:38:28] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:38:31] INFO [pcbuilder.views:29] None
[28/Oct/2014 10:38:31] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:38:32] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:38:44] INFO [pcbuilder.views:29] None
[28/Oct/2014 10:38:44] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:38:44] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:45:07] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:45:13] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:45:13] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:45:13] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:45:29] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:45:33] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:45:36] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:45:40] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:45:40] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:45:41] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:45:46] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:45:46] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:45:46] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:45:46] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:45:47] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:45:47] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:45:47] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:45:47] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:45:47] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:45:47] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:45:47] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:45:47] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:45:48] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:46:13] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:46:13] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:46:13] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:46:54] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 29
    logger.info(categorie.0)
                          ^
SyntaxError: invalid syntax
[28/Oct/2014 10:46:54] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:47:02] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:47:08] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:47:44] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:47:45] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:47:45] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:47:45] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:50:41] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:50:41] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:50:41] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 40, in detail
    context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 23, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 162, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 201, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 290, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 175, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 266, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 372, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 588, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '('product')' from 'request.GET.get('product')'
[28/Oct/2014 10:50:43] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:51:10] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:51:13] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:51:13] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:51:13] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:55:39] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/APc/urls.py", line 6, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 260, in urls
    return self.get_urls(), self.app_name, self.name
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 221, in get_urls
    self.check_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 166, in check_dependencies
    raise ImproperlyConfigured("Put 'django.contrib.auth.context_processors.auth' "
ImproperlyConfigured: Put 'django.contrib.auth.context_processors.auth' in your TEMPLATE_CONTEXT_PROCESSORS setting in order to use the admin application.
[28/Oct/2014 10:55:39] ERROR [django.request:231] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 72, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 614, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 489, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 338, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/robin/Work/School/A-Pc/Website/APc/urls.py", line 6, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 260, in urls
    return self.get_urls(), self.app_name, self.name
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 221, in get_urls
    self.check_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 166, in check_dependencies
    raise ImproperlyConfigured("Put 'django.contrib.auth.context_processors.auth' "
ImproperlyConfigured: Put 'django.contrib.auth.context_processors.auth' in your TEMPLATE_CONTEXT_PROCESSORS setting in order to use the admin application.
[28/Oct/2014 10:56:29] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 340, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 222, in resolve
    kwargs.update(self.default_args)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
[28/Oct/2014 10:56:29] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:57:13] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:57:16] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:57:18] INFO [pcbuilder.views:29] 
[28/Oct/2014 10:57:18] INFO [pcbuilder.views:30] test
[28/Oct/2014 10:57:18] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 10:59:19] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 41, in detail
    context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 23, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
TypeError: render_to_string() got multiple values for keyword argument 'context_instance'
[28/Oct/2014 10:59:21] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:00:29] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:00:30] ERROR [django.request:231] Internal Server Error: /detail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 40, in detail
    return render_to_response('detail.html', {'Processoren': processoren} |categorie | product,
TypeError: unsupported operand type(s) for |: 'dict' and 'unicode'
[28/Oct/2014 11:00:31] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:02:11] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:02:13] INFO [pcbuilder.views:29] 
[28/Oct/2014 11:02:13] INFO [pcbuilder.views:30] test
[28/Oct/2014 11:02:13] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:02:46] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:02:48] INFO [pcbuilder.views:29] 
[28/Oct/2014 11:02:48] INFO [pcbuilder.views:30] test
[28/Oct/2014 11:02:48] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:03:12] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:03:13] INFO [pcbuilder.views:29] 
[28/Oct/2014 11:03:13] INFO [pcbuilder.views:30] test
[28/Oct/2014 11:03:14] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:03:58] INFO [pcbuilder.views:29] 
[28/Oct/2014 11:03:58] INFO [pcbuilder.views:30] test
[28/Oct/2014 11:03:58] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:04:00] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:04:01] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:04:03] INFO [pcbuilder.views:29] 
[28/Oct/2014 11:04:03] INFO [pcbuilder.views:30] test
[28/Oct/2014 11:04:03] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:06:37] INFO [pcbuilder.views:29] 
[28/Oct/2014 11:06:37] INFO [pcbuilder.views:30] test
[28/Oct/2014 11:06:37] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:06:38] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:06:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:06:41] INFO [pcbuilder.views:29] 
[28/Oct/2014 11:06:41] INFO [pcbuilder.views:30] test
[28/Oct/2014 11:06:41] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:07:25] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:07:27] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:09:01] INFO [pcbuilder.views:41] Moederborden
[28/Oct/2014 11:09:01] INFO [pcbuilder.views:42] test
[28/Oct/2014 11:09:01] INFO [pcbuilder.views:41] Moederborden
[28/Oct/2014 11:09:01] INFO [pcbuilder.views:42] test
[28/Oct/2014 11:09:01] INFO [pcbuilder.views:41] Moederborden
[28/Oct/2014 11:09:01] INFO [pcbuilder.views:42] test
[28/Oct/2014 11:09:02] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:09:04] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:09:05] INFO [pcbuilder.views:41] Moederborden
[28/Oct/2014 11:09:05] INFO [pcbuilder.views:42] test
[28/Oct/2014 11:09:05] INFO [pcbuilder.views:41] Moederborden
[28/Oct/2014 11:09:05] INFO [pcbuilder.views:42] test
[28/Oct/2014 11:09:05] INFO [pcbuilder.views:41] Moederborden
[28/Oct/2014 11:09:05] INFO [pcbuilder.views:42] test
[28/Oct/2014 11:09:05] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:10:02] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:10:09] INFO [pcbuilder.views:29]  Moederborden
[28/Oct/2014 11:10:09] INFO [pcbuilder.views:30] test
[28/Oct/2014 11:10:10] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:10:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:10:41] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:10:42] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:10:47] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:12:09] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:12:14] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:12:38] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:12:40] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:12:43] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:13:29] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:13:30] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:13:33] INFO [pcbuilder.views:31] Moederborden
[28/Oct/2014 11:13:33] INFO [pcbuilder.views:32] test
[28/Oct/2014 11:13:34] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:15:30] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:15:38] INFO [pcbuilder.views:32] True
[28/Oct/2014 11:15:38] INFO [pcbuilder.views:33] test
[28/Oct/2014 11:15:39] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:16:25] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:17:35] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:17:38] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:17:40] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:17:57] WARNING [django.request:143] Not Found: /favicon.ico
[28/Oct/2014 11:18:19] WARNING [django.request:143] Not Found: /favicon.ico
